version: "3.8"

services:
  database:
    image: postgres:14-alpine
    container_name: tasks_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tasksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: tasks_backend
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=tasksdb
      - PORT=8080
    networks:
      - app-network
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    container_name: tasks_frontend
    networks:
      - app-network
    expose:
      - "3000"

  nginx:
    build:
      context: ./nginx
    container_name: tasks_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
